//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportInfo
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Code3 { get; set; }
        public string Code4 { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string FrameOfAxes { get; set; }
        public string RunwayLength { get; set; }
        public string AreaParentCode { get; set; }
        public string AreaCode { get; set; }
        public bool DeletedFlag { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int ModifiedUserId { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public string CreateSource { get; set; }
        public bool IsTransport { get; set; }
    }
}
