//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessCertificate
    {
        public int ID { get; set; }
        public string CompanyCode3 { get; set; }
        public string LicenseNo { get; set; }
        public string BaseAirport { get; set; }
        public string ConpanyType { get; set; }
        public Nullable<double> RegisteredCapital { get; set; }
        public Nullable<double> CapitalLimit { get; set; }
        public string Legalperson { get; set; }
        public string ManageItemsScope { get; set; }
        public Nullable<int> DealLine { get; set; }
        public Nullable<System.DateTime> PresentationDate { get; set; }
        public string LicensedSeal { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
