//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessLicense
    {
        public int ID { get; set; }
        public string CompanyCode3 { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string RegisterAddress { get; set; }
        public string CorporateRepresentative { get; set; }
        public Nullable<double> RegisteredCapital { get; set; }
        public Nullable<int> Dealline { get; set; }
        public string ContactPerson { get; set; }
        public string LegalPerson { get; set; }
        public string LegalCardNo { get; set; }
        public string LegalAddress { get; set; }
        public string LegalTelePhone { get; set; }
        public string LegalCardImg { get; set; }
        public string LegalClientele { get; set; }
        public string LegalDelegateImg { get; set; }
        public string DelegateName { get; set; }
        public string DelegateCardNo { get; set; }
        public string DelegateAddress { get; set; }
        public string DelegateTelePhone { get; set; }
        public string DelegateCardImg { get; set; }
    }
}
