//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string CompanyCode3 { get; set; }
        public string CompanyCode2 { get; set; }
        public string EnglishName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> DomesticFlag { get; set; }
        public string Surname { get; set; }
        public string SITAAddress { get; set; }
        public string AFTNAddress { get; set; }
        public Nullable<int> ReferSourceID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
