//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int CompanyID { get; set; }
        public string CompanyCode3 { get; set; }
        public string CompanyCode2 { get; set; }
        public string EnglishName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Summary { get; set; }
        public string SummaryCode { get; set; }
        public Nullable<int> Catalog { get; set; }
        public Nullable<int> ActorID { get; set; }
        public string State { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.DateTime> RegisterTime { get; set; }
        public string RegisterAddress { get; set; }
        public string CorporateRepresentative { get; set; }
        public Nullable<double> RegisteredCapital { get; set; }
        public string Dealline { get; set; }
        public string ContactPerson { get; set; }
        public string LegalPerson { get; set; }
        public string LegalCardNo { get; set; }
        public string LegalAddress { get; set; }
        public string LegalTelePhone { get; set; }
        public string LegalCardImg { get; set; }
        public string LegalClientele { get; set; }
        public string LegalDelegateImg { get; set; }
        public string DelegateCardNo { get; set; }
        public string DelegateAddress { get; set; }
        public string DelegateTelePhone { get; set; }
        public string DelegateCardImg { get; set; }
        public string LicenseNo { get; set; }
        public string BaseAirport { get; set; }
        public string CompanyType { get; set; }
        public Nullable<double> RegisteredFund { get; set; }
        public Nullable<double> CapitalLimit { get; set; }
        public string Legalperson1 { get; set; }
        public string ManageItemsScope { get; set; }
        public string DealLine1 { get; set; }
        public Nullable<System.DateTime> PresentationDate { get; set; }
        public string LicensedSeal { get; set; }
        public string FirmName { get; set; }
        public string FirmCode { get; set; }
        public string FirmAddress { get; set; }
        public string BaseAirportCode { get; set; }
        public string LicensingAuthority { get; set; }
    }
}
