//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySummary
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string SummaryCode { get; set; }
        public string State { get; set; }
        public Nullable<int> ActorID { get; set; }
    }
}
