//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentFlightPlan
    {
        public System.Guid CurrentFlightPlanID { get; set; }
        public string RepetPlanID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> ActualStartTime { get; set; }
        public Nullable<System.DateTime> ActualEndTime { get; set; }
        public string PlanState { get; set; }
        public Nullable<int> ActorID { get; set; }
        public int Creator { get; set; }
        public string CreatorName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string FlightPlanID { get; set; }
        public string Pilot { get; set; }
        public Nullable<int> AircraftNum { get; set; }
        public bool DeletedFlag { get; set; }
        public string ContractWay { get; set; }
        public string ActorName { get; set; }
        public string FlightType { get; set; }
        public string AircraftType { get; set; }
        public string SsrCode { get; set; }
        public string CallSign { get; set; }
        public string ADEP { get; set; }
        public string ADES { get; set; }
        public string AirportText { get; set; }
        public string AirlineWorkText { get; set; }
    }
}
