//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_Detail
    {
        public string ID { get; set; }
        public string MasterID { get; set; }
        public string RepetPlanID { get; set; }
        public string PointName { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<short> RaidusMile { get; set; }
        public int Sort { get; set; }
    }
}
