//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public string LinkUrl { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string ImageUrl { get; set; }
        public byte OrderSort { get; set; }
        public byte MenuLevel { get; set; }
        public string MenuCode { get; set; }
    }
}
