//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot
    {
        public string pilot1 { get; set; }
        public string pilotcardNo { get; set; }
        public System.DateTime datatime { get; set; }
        public string phoneNo { get; set; }
        public string licensesort { get; set; }
        public string licenseNo { get; set; }
        public string sign { get; set; }
        public Nullable<byte> sex { get; set; }
        public string companyName { get; set; }
        public string licenseImg { get; set; }
    }
}
