//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilot
    {
        public int ID { get; set; }
        public string Pilots { get; set; }
        public string PilotCardNo { get; set; }
        public System.DateTime PilotDT { get; set; }
        public string PhoneNo { get; set; }
        public string Licensesort { get; set; }
        public string LicenseNo { get; set; }
        public string Sign { get; set; }
        public Nullable<byte> Sex { get; set; }
        public string CompanyName { get; set; }
        public string LicenseImg { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> PilotAge { get; set; }
        public Nullable<System.DateTime> LicenseTime { get; set; }
    }
}
