//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepetPlanNew
    {
        public int RepetPlanID { get; set; }
        public string CompanyName { get; set; }
        public string FlightArea { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string FlightType { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string AircraftType { get; set; }
        public int Creator { get; set; }
        public string CreateName { get; set; }
        public string AuditName { get; set; }
        public string Code { get; set; }
        public string CallSign { get; set; }
        public bool IsUrgentTask { get; set; }
        public bool IsCrossArea { get; set; }
    }
}
