//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string DealUser { get; set; }
        public Nullable<int> ResourceType { get; set; }
        public string UsefulTime { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SenderId { get; set; }
    }
}
